name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Workflow dijalankan saat ada push ke branch 'main'
  pull_request:
    branches:
      - main  # Workflow dijalankan saat ada PR ke branch 'main'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.9  # Tentukan versi Terraform yang diinginkan

      # Step 3: Cache Terraform providers
      - name: Cache Terraform providers
        uses: actions/cache@v2
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      # Step 4: Set up GCP credentials from GitHub Secrets
      - name: Set up GCP credentials
        run: echo "${{ secrets.GCP_CREDENTIALS }}" > "${{ github.workspace }}/gcp_credentials.json"

      # Step 5: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ github.workspace }}/credentials.json"

      # Step 6: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 7: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      # Step 8: Terraform Output (optional)
      - name: Terraform Output
        run: terraform output
